apiVersion: apps/v1
kind: Deployment
metadata:
  name: myip-deployment
  labels:
    app: myip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myip
  template:
    metadata:
      labels:
        app: myip
    spec:
      containers:
        - name: myip-container
          image: your-ip:v1.0
          ports:
            - containerPort: 8000
          env:
            - name: TYPE
              value: "ipapi"